"""
Persistencia: SQLite en local, Postgres (Supabase) en la nube
-------------------------------------------------------------
El backend se elige solo: si existe DATABASE_URL (variable de entorno o
secret de Streamlit), se conecta a Postgres; si no, usa el archivo local
checklist_data.db. Así el mismo código corre en la laptop sin configurar
nada y en Streamlit Cloud apuntando a Supabase.

Esquema (campañas → folios → revisiones → respuestas):
- campanas: agrupador de 10-20 folios; estado abierta/cerrada solo
  controla si aparece en el selector de captura.
- folios: el folio (= número de OT) es único; cliente y campaña son
  atributos del folio, no de cada revisión. Reasignar campaña mueve el
  folio con todo su historial.
- revisiones/respuestas: igual que siempre, colgando del folio.

Concurrencia (varios evaluadores guardando a la vez):
- SQLite: WAL + BEGIN IMMEDIATE serializa los guardados.
- Postgres: el UPSERT del folio toma el candado de fila dentro de la
  transacción, así dos guardados del mismo folio se forman en fila y el
  número de revisión nunca se duplica.
- UNIQUE(folio_id, revision) como red de seguridad en ambos casos.

Las consultas usan placeholders '?' y se convierten a '%s' para Postgres.
"""

import os
import sqlite3

DB_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "checklist_data.db")


def _database_url():
    url = os.environ.get("DATABASE_URL", "")
    if url:
        return url
    try:
        import streamlit as st
        return st.secrets.get("DATABASE_URL", "")
    except Exception:
        return ""


def _is_postgres():
    return bool(_database_url())


def _connect():
    if _is_postgres():
        import psycopg2
        import psycopg2.extras
        conn = psycopg2.connect(_database_url(),
                                cursor_factory=psycopg2.extras.RealDictCursor)
        return conn
    conn = sqlite3.connect(DB_FILE, timeout=30, isolation_level=None)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=30000")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


def _sql(query):
    return query.replace("?", "%s") if _is_postgres() else query


def _fetchall(conn, query, params=()):
    if _is_postgres():
        with conn.cursor() as cur:
            cur.execute(_sql(query), params)
            return [dict(r) for r in cur.fetchall()]
    return [dict(r) for r in conn.execute(query, params).fetchall()]


def _fetchone(conn, query, params=()):
    rows = _fetchall(conn, query, params)
    return rows[0] if rows else None


def init_db():
    pk = ("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if _is_postgres() else "INTEGER PRIMARY KEY AUTOINCREMENT")
    ddl = [
        f"""CREATE TABLE IF NOT EXISTS campanas (
            id {pk},
            nombre TEXT NOT NULL UNIQUE,
            estado TEXT NOT NULL DEFAULT 'abierta'
        )""",
        f"""CREATE TABLE IF NOT EXISTS folios (
            id {pk},
            folio TEXT NOT NULL UNIQUE,
            cliente TEXT,
            campana_id BIGINT REFERENCES campanas(id)
        )""",
        f"""CREATE TABLE IF NOT EXISTS revisiones (
            id {pk},
            folio_id BIGINT NOT NULL REFERENCES folios(id) ON DELETE CASCADE,
            revision INTEGER NOT NULL,
            evaluador TEXT,
            fecha TEXT NOT NULL,
            resultado TEXT NOT NULL,
            UNIQUE(folio_id, revision)
        )""",
        f"""CREATE TABLE IF NOT EXISTS respuestas (
            id {pk},
            revision_id BIGINT NOT NULL REFERENCES revisiones(id) ON DELETE CASCADE,
            item_id TEXT NOT NULL,
            status TEXT NOT NULL,
            motivo TEXT
        )""",
        "CREATE INDEX IF NOT EXISTS idx_revisiones_folio ON revisiones(folio_id)",
        "CREATE INDEX IF NOT EXISTS idx_respuestas_revision ON respuestas(revision_id)",
        "CREATE INDEX IF NOT EXISTS idx_folios_campana ON folios(campana_id)",
    ]
    conn = _connect()
    try:
        if _is_postgres():
            with conn.cursor() as cur:
                for stmt in ddl:
                    cur.execute(stmt)
            conn.commit()
        else:
            for stmt in ddl:
                conn.execute(stmt)
    finally:
        conn.close()


# ---------------------------------------------------------------------
# Campañas
# ---------------------------------------------------------------------

def get_campanas(solo_abiertas=False):
    query = "SELECT id, nombre, estado FROM campanas"
    if solo_abiertas:
        query += " WHERE estado = 'abierta'"
    query += " ORDER BY nombre"
    conn = _connect()
    try:
        return _fetchall(conn, query)
    finally:
        conn.close()


def crear_campana(nombre):
    """Crea la campaña (o regresa la existente con ese nombre)."""
    nombre = nombre.strip()
    conn = _connect()
    try:
        existente = _fetchone(conn, "SELECT id FROM campanas WHERE lower(nombre) = lower(?)", (nombre,))
        if existente:
            return existente["id"]
        if _is_postgres():
            with conn.cursor() as cur:
                cur.execute(_sql("INSERT INTO campanas (nombre) VALUES (?) RETURNING id"), (nombre,))
                nuevo_id = cur.fetchone()["id"]
            conn.commit()
            return nuevo_id
        cur = conn.execute("INSERT INTO campanas (nombre) VALUES (?)", (nombre,))
        return cur.lastrowid
    finally:
        conn.close()


def cambiar_estado_campana(campana_id, estado):
    conn = _connect()
    try:
        if _is_postgres():
            with conn.cursor() as cur:
                cur.execute(_sql("UPDATE campanas SET estado = ? WHERE id = ?"), (estado, campana_id))
            conn.commit()
        else:
            conn.execute("UPDATE campanas SET estado = ? WHERE id = ?", (estado, campana_id))
    finally:
        conn.close()


# ---------------------------------------------------------------------
# Folios y revisiones
# ---------------------------------------------------------------------

def get_folio(folio):
    folio = folio.strip()
    if not folio:
        return None
    conn = _connect()
    try:
        return _fetchone(conn, """
            SELECT f.id, f.folio, f.cliente, f.campana_id,
                   c.nombre AS campana, c.estado AS campana_estado
            FROM folios f
            LEFT JOIN campanas c ON c.id = f.campana_id
            WHERE f.folio = ?
        """, (folio,))
    finally:
        conn.close()


def get_revisiones(folio):
    """Todas las revisiones de un folio, de la más antigua a la más reciente."""
    folio = folio.strip()
    if not folio:
        return []
    conn = _connect()
    try:
        rev_rows = _fetchall(conn, """
            SELECT r.id, r.revision, r.evaluador, r.fecha, r.resultado
            FROM revisiones r JOIN folios f ON f.id = r.folio_id
            WHERE f.folio = ? ORDER BY r.revision ASC
        """, (folio,))
        revisiones = []
        for row in rev_rows:
            resp = _fetchall(conn,
                             "SELECT item_id, status, motivo FROM respuestas WHERE revision_id = ?",
                             (row["id"],))
            revisiones.append({
                "revision": row["revision"],
                "fecha": row["fecha"],
                "evaluador": row["evaluador"] or "",
                "resultado": row["resultado"],
                "respuestas": {
                    r["item_id"]: {"status": r["status"], "motivo": r["motivo"] or ""}
                    for r in resp
                },
            })
        return revisiones
    finally:
        conn.close()


def save_revision(folio, cliente, campana_id, evaluador, respuestas, resultado, fecha):
    """
    Da de alta o actualiza el folio (cliente/campaña) e inserta la nueva
    revisión, todo en una transacción. El número de revisión se calcula
    dentro de la misma transacción para que dos guardados simultáneos
    del mismo folio no se pisen.
    """
    folio = folio.strip()
    conn = _connect()
    try:
        if _is_postgres():
            with conn.cursor() as cur:
                # El upsert toma el candado de fila del folio dentro de la tx
                cur.execute(_sql("""
                    INSERT INTO folios (folio, cliente, campana_id) VALUES (?, ?, ?)
                    ON CONFLICT (folio) DO UPDATE
                        SET cliente = EXCLUDED.cliente, campana_id = EXCLUDED.campana_id
                    RETURNING id
                """), (folio, cliente, campana_id))
                folio_id = cur.fetchone()["id"]
                cur.execute(_sql(
                    "SELECT COALESCE(MAX(revision), 0) AS max_rev FROM revisiones WHERE folio_id = ?"
                ), (folio_id,))
                revision_num = cur.fetchone()["max_rev"] + 1
                cur.execute(_sql("""
                    INSERT INTO revisiones (folio_id, revision, evaluador, fecha, resultado)
                    VALUES (?, ?, ?, ?, ?) RETURNING id
                """), (folio_id, revision_num, evaluador, fecha, resultado))
                revision_id = cur.fetchone()["id"]
                cur.executemany(_sql(
                    "INSERT INTO respuestas (revision_id, item_id, status, motivo) VALUES (?, ?, ?, ?)"
                ), [(revision_id, item_id, r["status"], r.get("motivo", ""))
                    for item_id, r in respuestas.items()])
            conn.commit()
            return revision_num

        conn.execute("BEGIN IMMEDIATE")
        try:
            row = conn.execute("SELECT id FROM folios WHERE folio = ?", (folio,)).fetchone()
            if row:
                folio_id = row["id"]
                conn.execute("UPDATE folios SET cliente = ?, campana_id = ? WHERE id = ?",
                             (cliente, campana_id, folio_id))
            else:
                cur = conn.execute("INSERT INTO folios (folio, cliente, campana_id) VALUES (?, ?, ?)",
                                   (folio, cliente, campana_id))
                folio_id = cur.lastrowid
            row = conn.execute(
                "SELECT COALESCE(MAX(revision), 0) AS max_rev FROM revisiones WHERE folio_id = ?",
                (folio_id,)).fetchone()
            revision_num = row["max_rev"] + 1
            cur = conn.execute(
                "INSERT INTO revisiones (folio_id, revision, evaluador, fecha, resultado) VALUES (?, ?, ?, ?, ?)",
                (folio_id, revision_num, evaluador, fecha, resultado))
            revision_id = cur.lastrowid
            conn.executemany(
                "INSERT INTO respuestas (revision_id, item_id, status, motivo) VALUES (?, ?, ?, ?)",
                [(revision_id, item_id, r["status"], r.get("motivo", ""))
                 for item_id, r in respuestas.items()])
            conn.execute("COMMIT")
        except Exception:
            conn.execute("ROLLBACK")
            raise
        return revision_num
    finally:
        conn.close()


# ---------------------------------------------------------------------
# Consultas para el dashboard
# ---------------------------------------------------------------------

def _filtro_campana(filtro):
    """filtro: 'todas' | None (sin campaña) | id de campaña."""
    if filtro == "todas":
        return "", ()
    if filtro is None:
        return " AND f.campana_id IS NULL", ()
    return " AND f.campana_id = ?", (filtro,)


def get_revisiones_dashboard(filtro="todas"):
    """Una fila por revisión: folio, cliente, campana, revision, resultado, fecha, evaluador."""
    where, params = _filtro_campana(filtro)
    conn = _connect()
    try:
        return _fetchall(conn, f"""
            SELECT f.folio, f.cliente, c.nombre AS campana,
                   r.revision, r.resultado, r.fecha, r.evaluador
            FROM revisiones r
            JOIN folios f ON f.id = r.folio_id
            LEFT JOIN campanas c ON c.id = f.campana_id
            WHERE 1=1{where}
            ORDER BY f.folio, r.revision
        """, params)
    finally:
        conn.close()


def get_respuestas_dashboard(filtro="todas"):
    """Una fila por respuesta: folio, revision, item_id, status."""
    where, params = _filtro_campana(filtro)
    conn = _connect()
    try:
        return _fetchall(conn, f"""
            SELECT f.folio, r.revision, a.item_id, a.status
            FROM respuestas a
            JOIN revisiones r ON r.id = a.revision_id
            JOIN folios f ON f.id = r.folio_id
            WHERE 1=1{where}
        """, params)
    finally:
        conn.close()
