"""
Persistencia: SQLite en local, Postgres (Supabase) en la nube
-------------------------------------------------------------
El backend se elige solo: si existe DATABASE_URL (variable de entorno o
secret de Streamlit), se conecta a Postgres; si no, usa el archivo local
checklist_data.db. Así el mismo código corre en la laptop sin configurar
nada y en Streamlit Cloud apuntando a Supabase.

Esquema (campañas → folios → revisiones → respuestas):
- campanas: agrupador de 10-20 folios; estado abierta/cerrada solo
  controla si aparece en el selector de captura.
- folios: el folio (= número de OT) es único; cliente y campaña son
  atributos del folio, no de cada revisión. Reasignar campaña mueve el
  folio con todo su historial.
- revisiones/respuestas: igual que siempre, colgando del folio.

Concurrencia (varios evaluadores guardando a la vez):
- SQLite: WAL + BEGIN IMMEDIATE serializa los guardados.
- Postgres: el UPSERT del folio toma el candado de fila dentro de la
  transacción, así dos guardados del mismo folio se forman en fila y el
  número de revisión nunca se duplica.
- UNIQUE(folio_id, revision) como red de seguridad en ambos casos.

Las consultas usan placeholders '?' y se convierten a '%s' para Postgres.
"""

import os
import sqlite3
import threading
import uuid
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

DB_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "checklist_data.db")
_TZ = ZoneInfo("America/Mexico_City")


def _ahora():
    return datetime.now(_TZ).strftime("%Y-%m-%d %H:%M:%S")


def _database_url():
    url = os.environ.get("DATABASE_URL", "")
    if url:
        return url
    try:
        import streamlit as st
        return st.secrets.get("DATABASE_URL", "")
    except Exception:
        return ""


def _is_postgres():
    return bool(_database_url())


def _connect():
    if _is_postgres():
        import psycopg2
        import psycopg2.extras
        conn = psycopg2.connect(_database_url(),
                                cursor_factory=psycopg2.extras.RealDictCursor)
        return conn
    conn = sqlite3.connect(DB_FILE, timeout=30, isolation_level=None)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=30000")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


def _sql(query):
    return query.replace("?", "%s") if _is_postgres() else query


def _fetchall(conn, query, params=()):
    if _is_postgres():
        with conn.cursor() as cur:
            cur.execute(_sql(query), params)
            return [dict(r) for r in cur.fetchall()]
    return [dict(r) for r in conn.execute(query, params).fetchall()]


def _fetchone(conn, query, params=()):
    rows = _fetchall(conn, query, params)
    return rows[0] if rows else None


_init_lock = threading.Lock()
_esquema_listo = False


def init_db():
    """Prepara el esquema UNA sola vez por proceso.

    Antes corría en CADA recarga de Streamlit (y Streamlit recarga en cada
    clic). Con varios usuarios a la vez, el DDL (CREATE/ALTER TABLE) chocaba
    entre sí y con los guardados, provocando deadlocks en Postgres. Ahora el
    primer llamado crea/migra el esquema y los siguientes salen de inmediato;
    el candado evita que en el arranque dos sesiones lo corran en paralelo.
    """
    global _esquema_listo
    if _esquema_listo:
        return
    with _init_lock:
        if _esquema_listo:
            return
        _crear_esquema()
        _esquema_listo = True


def _crear_esquema():
    pk = ("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
          if _is_postgres() else "INTEGER PRIMARY KEY AUTOINCREMENT")
    ddl = [
        f"""CREATE TABLE IF NOT EXISTS campanas (
            id {pk},
            nombre TEXT NOT NULL UNIQUE,
            estado TEXT NOT NULL DEFAULT 'abierta'
        )""",
        f"""CREATE TABLE IF NOT EXISTS folios (
            id {pk},
            folio TEXT NOT NULL UNIQUE,
            cliente TEXT,
            campana_id BIGINT REFERENCES campanas(id)
        )""",
        f"""CREATE TABLE IF NOT EXISTS revisiones (
            id {pk},
            folio_id BIGINT NOT NULL REFERENCES folios(id) ON DELETE CASCADE,
            revision INTEGER NOT NULL,
            tipo TEXT NOT NULL DEFAULT 'segundo',
            evaluador TEXT,
            fecha TEXT NOT NULL,
            resultado TEXT NOT NULL,
            UNIQUE(folio_id, revision)
        )""",
        f"""CREATE TABLE IF NOT EXISTS respuestas (
            id {pk},
            revision_id BIGINT NOT NULL REFERENCES revisiones(id) ON DELETE CASCADE,
            item_id TEXT NOT NULL,
            status TEXT NOT NULL,
            motivo TEXT
        )""",
        f"""CREATE TABLE IF NOT EXISTS eventos (
            id {pk},
            fecha TEXT NOT NULL,
            usuario TEXT,
            email TEXT,
            rol TEXT,
            accion TEXT NOT NULL,
            folio TEXT,
            detalle TEXT
        )""",
        """CREATE TABLE IF NOT EXISTS presencia (
            usuario TEXT PRIMARY KEY,
            email TEXT,
            rol TEXT,
            last_seen TEXT NOT NULL
        )""",
        # Presencia POR FOLIO: qué 2do check está trabajando cada evaluador
        # ahora mismo, para avisar a los demás y no duplicar esfuerzo.
        """CREATE TABLE IF NOT EXISTS en_revision (
            usuario TEXT PRIMARY KEY,
            folio TEXT NOT NULL,
            last_seen TEXT NOT NULL
        )""",
        # Formulario del checklist, editable desde el gestor (admin).
        """CREATE TABLE IF NOT EXISTS checklist_bloques (
            clave TEXT PRIMARY KEY,
            nombre TEXT NOT NULL,
            orden INTEGER NOT NULL DEFAULT 0
        )""",
        """CREATE TABLE IF NOT EXISTS checklist_items (
            clave TEXT PRIMARY KEY,
            bloque TEXT NOT NULL,
            categoria TEXT NOT NULL,
            texto TEXT NOT NULL,
            orden INTEGER NOT NULL DEFAULT 0,
            activo INTEGER NOT NULL DEFAULT 1
        )""",
        "CREATE INDEX IF NOT EXISTS idx_revisiones_folio ON revisiones(folio_id)",
        "CREATE INDEX IF NOT EXISTS idx_respuestas_revision ON respuestas(revision_id)",
        "CREATE INDEX IF NOT EXISTS idx_folios_campana ON folios(campana_id)",
        "CREATE INDEX IF NOT EXISTS idx_eventos_fecha ON eventos(fecha)",
    ]
    conn = _connect()
    try:
        if _is_postgres():
            with conn.cursor() as cur:
                for stmt in ddl:
                    cur.execute(stmt)
                # Bases creadas antes del 1er check del diseñador
                cur.execute("ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS "
                            "tipo TEXT NOT NULL DEFAULT 'segundo'")
            conn.commit()
        else:
            for stmt in ddl:
                conn.execute(stmt)
            try:
                conn.execute("ALTER TABLE revisiones ADD COLUMN "
                             "tipo TEXT NOT NULL DEFAULT 'segundo'")
            except sqlite3.OperationalError:
                pass  # la columna ya existe
    finally:
        conn.close()
    _seed_checklist()


# ---------------------------------------------------------------------
# Checklist (formulario editable): bloques e ítems
# ---------------------------------------------------------------------

def _seed_checklist():
    """Siembra bloques e ítems desde catalogo.py la primera vez (tablas
    vacías). Usa ON CONFLICT/OR IGNORE para ser idempotente aunque dos
    instancias arranquen a la vez."""
    conn = _connect()
    try:
        row = _fetchone(conn, "SELECT COUNT(*) AS n FROM checklist_items")
        if row and int(row["n"]) > 0:
            return
        from catalogo import BLOQUES, CHECKLIST_ITEMS
        bloques = [(clave, nombre, i) for i, (clave, nombre) in enumerate(BLOQUES)]
        items = [(it["id"], it["bloque"], it["categoria"], it["texto"], i, 1)
                 for i, it in enumerate(CHECKLIST_ITEMS)]
        if _is_postgres():
            bsql = ("INSERT INTO checklist_bloques (clave, nombre, orden) "
                    "VALUES (?, ?, ?) ON CONFLICT (clave) DO NOTHING")
            isql = ("INSERT INTO checklist_items (clave, bloque, categoria, texto, orden, activo) "
                    "VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT (clave) DO NOTHING")
            with conn.cursor() as cur:
                cur.executemany(_sql(bsql), bloques)
                cur.executemany(_sql(isql), items)
            conn.commit()
        else:
            conn.executemany("INSERT OR IGNORE INTO checklist_bloques (clave, nombre, orden) "
                             "VALUES (?, ?, ?)", bloques)
            conn.executemany("INSERT OR IGNORE INTO checklist_items "
                             "(clave, bloque, categoria, texto, orden, activo) "
                             "VALUES (?, ?, ?, ?, ?, ?)", items)
    finally:
        conn.close()


def get_bloques():
    """Bloques del checklist ordenados: lista de (clave, nombre)."""
    conn = _connect()
    try:
        rows = _fetchall(conn, "SELECT clave, nombre FROM checklist_bloques "
                               "ORDER BY orden, clave")
        return [(r["clave"], r["nombre"]) for r in rows]
    finally:
        conn.close()


def get_checklist(solo_activos=True):
    """Ítems del checklist ordenados; forma compatible con CHECKLIST_ITEMS
    (id, bloque, categoria, texto) más orden y activo."""
    conn = _connect()
    try:
        q = ("SELECT clave, bloque, categoria, texto, orden, activo "
             "FROM checklist_items")
        if solo_activos:
            q += " WHERE activo = 1"
        q += " ORDER BY orden, clave"
        return [{"id": r["clave"], "bloque": r["bloque"], "categoria": r["categoria"],
                 "texto": r["texto"], "orden": r["orden"], "activo": int(r["activo"])}
                for r in _fetchall(conn, q)]
    finally:
        conn.close()


def get_item_texto():
    """{clave: texto} de TODOS los ítems (activos e inactivos), para poder
    mostrar respuestas históricas de puntos que ya se desactivaron."""
    conn = _connect()
    try:
        return {r["clave"]: r["texto"]
                for r in _fetchall(conn, "SELECT clave, texto FROM checklist_items")}
    finally:
        conn.close()


def _upsert(conn, sql_pg, sql_sqlite, params):
    if _is_postgres():
        with conn.cursor() as cur:
            cur.execute(_sql(sql_pg), params)
        conn.commit()
    else:
        conn.execute(sql_sqlite, params)


def guardar_item(clave, bloque, categoria, texto, orden, activo):
    """Inserta o actualiza un punto del checklist."""
    conn = _connect()
    try:
        _upsert(
            conn,
            "INSERT INTO checklist_items (clave, bloque, categoria, texto, orden, activo) "
            "VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT (clave) DO UPDATE SET "
            "bloque=EXCLUDED.bloque, categoria=EXCLUDED.categoria, texto=EXCLUDED.texto, "
            "orden=EXCLUDED.orden, activo=EXCLUDED.activo",
            "INSERT INTO checklist_items (clave, bloque, categoria, texto, orden, activo) "
            "VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT(clave) DO UPDATE SET "
            "bloque=excluded.bloque, categoria=excluded.categoria, texto=excluded.texto, "
            "orden=excluded.orden, activo=excluded.activo",
            (clave, bloque, categoria, texto, int(orden), int(activo)),
        )
    finally:
        conn.close()


def crear_item(bloque, categoria, texto, orden):
    """Crea un punto nuevo con clave autogenerada única y estable."""
    clave = "item_" + uuid.uuid4().hex[:10]
    guardar_item(clave, bloque, categoria, texto, orden, 1)
    return clave


def guardar_bloque(clave, nombre, orden):
    conn = _connect()
    try:
        _upsert(
            conn,
            "INSERT INTO checklist_bloques (clave, nombre, orden) VALUES (?, ?, ?) "
            "ON CONFLICT (clave) DO UPDATE SET nombre=EXCLUDED.nombre, orden=EXCLUDED.orden",
            "INSERT INTO checklist_bloques (clave, nombre, orden) VALUES (?, ?, ?) "
            "ON CONFLICT(clave) DO UPDATE SET nombre=excluded.nombre, orden=excluded.orden",
            (clave, nombre, int(orden)),
        )
    finally:
        conn.close()


def crear_bloque(nombre, orden):
    clave = "bloque_" + uuid.uuid4().hex[:8]
    guardar_bloque(clave, nombre, orden)
    return clave


def eliminar_bloque(clave):
    """Borra un bloque solo si no tiene ítems; si los tiene, no hace nada."""
    conn = _connect()
    try:
        con_items = _fetchone(conn, "SELECT COUNT(*) AS n FROM checklist_items WHERE bloque = ?",
                              (clave,))
        if con_items and int(con_items["n"]) > 0:
            return False
        if _is_postgres():
            with conn.cursor() as cur:
                cur.execute(_sql("DELETE FROM checklist_bloques WHERE clave = ?"), (clave,))
            conn.commit()
        else:
            conn.execute("DELETE FROM checklist_bloques WHERE clave = ?", (clave,))
        return True
    finally:
        conn.close()


# ---------------------------------------------------------------------
# Campañas
# ---------------------------------------------------------------------

def get_campanas(solo_abiertas=False):
    query = "SELECT id, nombre, estado FROM campanas"
    if solo_abiertas:
        query += " WHERE estado = 'abierta'"
    query += " ORDER BY nombre"
    conn = _connect()
    try:
        return _fetchall(conn, query)
    finally:
        conn.close()


def crear_campana(nombre):
    """Crea la campaña (o regresa la existente con ese nombre)."""
    nombre = nombre.strip()
    conn = _connect()
    try:
        existente = _fetchone(conn, "SELECT id FROM campanas WHERE lower(nombre) = lower(?)", (nombre,))
        if existente:
            return existente["id"]
        if _is_postgres():
            with conn.cursor() as cur:
                cur.execute(_sql("INSERT INTO campanas (nombre) VALUES (?) RETURNING id"), (nombre,))
                nuevo_id = cur.fetchone()["id"]
            conn.commit()
            return nuevo_id
        cur = conn.execute("INSERT INTO campanas (nombre) VALUES (?)", (nombre,))
        return cur.lastrowid
    finally:
        conn.close()


def cambiar_estado_campana(campana_id, estado):
    conn = _connect()
    try:
        if _is_postgres():
            with conn.cursor() as cur:
                cur.execute(_sql("UPDATE campanas SET estado = ? WHERE id = ?"), (estado, campana_id))
            conn.commit()
        else:
            conn.execute("UPDATE campanas SET estado = ? WHERE id = ?", (estado, campana_id))
    finally:
        conn.close()


# ---------------------------------------------------------------------
# Folios y revisiones
# ---------------------------------------------------------------------

def get_folio(folio):
    folio = folio.strip()
    if not folio:
        return None
    conn = _connect()
    try:
        return _fetchone(conn, """
            SELECT f.id, f.folio, f.cliente, f.campana_id,
                   c.nombre AS campana, c.estado AS campana_estado
            FROM folios f
            LEFT JOIN campanas c ON c.id = f.campana_id
            WHERE f.folio = ?
        """, (folio,))
    finally:
        conn.close()


def get_revisiones(folio):
    """Todas las revisiones de un folio, de la más antigua a la más reciente."""
    folio = folio.strip()
    if not folio:
        return []
    conn = _connect()
    try:
        rev_rows = _fetchall(conn, """
            SELECT r.id, r.revision, r.tipo, r.evaluador, r.fecha, r.resultado
            FROM revisiones r JOIN folios f ON f.id = r.folio_id
            WHERE f.folio = ? ORDER BY r.revision ASC
        """, (folio,))
        revisiones = []
        for row in rev_rows:
            resp = _fetchall(conn,
                             "SELECT item_id, status, motivo FROM respuestas WHERE revision_id = ?",
                             (row["id"],))
            revisiones.append({
                "revision": row["revision"],
                "tipo": row["tipo"],
                "fecha": row["fecha"],
                "evaluador": row["evaluador"] or "",
                "resultado": row["resultado"],
                "respuestas": {
                    r["item_id"]: {"status": r["status"], "motivo": r["motivo"] or ""}
                    for r in resp
                },
            })
        return revisiones
    finally:
        conn.close()


def save_revision(folio, cliente, campana_id, evaluador, respuestas, resultado, fecha,
                  tipo="segundo"):
    """
    Da de alta o actualiza el folio (cliente/campaña) e inserta la nueva
    revisión, todo en una transacción. El número de revisión se calcula
    dentro de la misma transacción para que dos guardados simultáneos
    del mismo folio no se pisen.
    """
    folio = folio.strip()
    conn = _connect()
    try:
        if _is_postgres():
            with conn.cursor() as cur:
                # El upsert toma el candado de fila del folio dentro de la tx
                cur.execute(_sql("""
                    INSERT INTO folios (folio, cliente, campana_id) VALUES (?, ?, ?)
                    ON CONFLICT (folio) DO UPDATE
                        SET cliente = EXCLUDED.cliente, campana_id = EXCLUDED.campana_id
                    RETURNING id
                """), (folio, cliente, campana_id))
                folio_id = cur.fetchone()["id"]
                cur.execute(_sql(
                    "SELECT COALESCE(MAX(revision), 0) AS max_rev FROM revisiones WHERE folio_id = ?"
                ), (folio_id,))
                revision_num = cur.fetchone()["max_rev"] + 1
                cur.execute(_sql("""
                    INSERT INTO revisiones (folio_id, revision, tipo, evaluador, fecha, resultado)
                    VALUES (?, ?, ?, ?, ?, ?) RETURNING id
                """), (folio_id, revision_num, tipo, evaluador, fecha, resultado))
                revision_id = cur.fetchone()["id"]
                cur.executemany(_sql(
                    "INSERT INTO respuestas (revision_id, item_id, status, motivo) VALUES (?, ?, ?, ?)"
                ), [(revision_id, item_id, r["status"], r.get("motivo", ""))
                    for item_id, r in respuestas.items()])
            conn.commit()
            return revision_num

        conn.execute("BEGIN IMMEDIATE")
        try:
            row = conn.execute("SELECT id FROM folios WHERE folio = ?", (folio,)).fetchone()
            if row:
                folio_id = row["id"]
                conn.execute("UPDATE folios SET cliente = ?, campana_id = ? WHERE id = ?",
                             (cliente, campana_id, folio_id))
            else:
                cur = conn.execute("INSERT INTO folios (folio, cliente, campana_id) VALUES (?, ?, ?)",
                                   (folio, cliente, campana_id))
                folio_id = cur.lastrowid
            row = conn.execute(
                "SELECT COALESCE(MAX(revision), 0) AS max_rev FROM revisiones WHERE folio_id = ?",
                (folio_id,)).fetchone()
            revision_num = row["max_rev"] + 1
            cur = conn.execute(
                "INSERT INTO revisiones (folio_id, revision, tipo, evaluador, fecha, resultado) VALUES (?, ?, ?, ?, ?, ?)",
                (folio_id, revision_num, tipo, evaluador, fecha, resultado))
            revision_id = cur.lastrowid
            conn.executemany(
                "INSERT INTO respuestas (revision_id, item_id, status, motivo) VALUES (?, ?, ?, ?)",
                [(revision_id, item_id, r["status"], r.get("motivo", ""))
                 for item_id, r in respuestas.items()])
            conn.execute("COMMIT")
        except Exception:
            conn.execute("ROLLBACK")
            raise
        return revision_num
    finally:
        conn.close()


# ---------------------------------------------------------------------
# Consultas para el dashboard
# ---------------------------------------------------------------------

def _filtro_campana(filtro):
    """filtro: 'todas' | None (sin campaña) | id de campaña."""
    if filtro == "todas":
        return "", ()
    if filtro is None:
        return " AND f.campana_id IS NULL", ()
    return " AND f.campana_id = ?", (filtro,)


def get_revisiones_dashboard(filtro="todas"):
    """Una fila por revisión: folio, cliente, campana, revision, tipo, resultado, fecha, evaluador."""
    where, params = _filtro_campana(filtro)
    conn = _connect()
    try:
        return _fetchall(conn, f"""
            SELECT f.folio, f.cliente, c.nombre AS campana,
                   r.revision, r.tipo, r.resultado, r.fecha, r.evaluador
            FROM revisiones r
            JOIN folios f ON f.id = r.folio_id
            LEFT JOIN campanas c ON c.id = f.campana_id
            WHERE 1=1{where}
            ORDER BY f.folio, r.revision
        """, params)
    finally:
        conn.close()


def get_pendientes():
    """Folios cuya última revisión es un 1er check del diseñador: la cola
    de pendientes de 2do check, del más antiguo al más reciente."""
    conn = _connect()
    try:
        return _fetchall(conn, """
            SELECT f.folio, f.cliente, c.nombre AS campana,
                   r.evaluador AS disenador, r.fecha
            FROM revisiones r
            JOIN folios f ON f.id = r.folio_id
            LEFT JOIN campanas c ON c.id = f.campana_id
            WHERE r.tipo = 'primer'
              AND r.id = (SELECT MAX(r2.id) FROM revisiones r2 WHERE r2.folio_id = r.folio_id)
            ORDER BY r.fecha ASC
        """)
    finally:
        conn.close()


def get_respuestas_dashboard(filtro="todas"):
    """Una fila por respuesta: folio, revision, item_id, status."""
    where, params = _filtro_campana(filtro)
    conn = _connect()
    try:
        return _fetchall(conn, f"""
            SELECT f.folio, r.revision, a.item_id, a.status
            FROM respuestas a
            JOIN revisiones r ON r.id = a.revision_id
            JOIN folios f ON f.id = r.folio_id
            WHERE 1=1{where}
        """, params)
    finally:
        conn.close()


# ---------------------------------------------------------------------
# Auditoría (bitácora de accesos y acciones)
# ---------------------------------------------------------------------

def registrar_evento(accion, usuario, folio=None, detalle=None):
    """Registra un evento en la bitácora. usuario es el dict {nombre, email,
    rol}. Best-effort: si algo falla, no interrumpe la app."""
    try:
        params = (_ahora(), usuario.get("nombre", ""), usuario.get("email", ""),
                  usuario.get("rol", ""), accion, folio, detalle)
        sql = ("INSERT INTO eventos (fecha, usuario, email, rol, accion, folio, detalle) "
               "VALUES (?, ?, ?, ?, ?, ?, ?)")
        conn = _connect()
        try:
            if _is_postgres():
                with conn.cursor() as cur:
                    cur.execute(_sql(sql), params)
                conn.commit()
            else:
                conn.execute(sql, params)
        finally:
            conn.close()
    except Exception:
        pass


def get_eventos(limite=2000):
    """Bitácora de eventos, del más reciente al más antiguo."""
    conn = _connect()
    try:
        return _fetchall(conn,
                         "SELECT fecha, usuario, email, rol, accion, folio, detalle "
                         "FROM eventos ORDER BY id DESC LIMIT ?", (limite,))
    finally:
        conn.close()


def registrar_presencia(usuario):
    """Actualiza 'última vez visto' del usuario (latido de presencia).
    Best-effort. Sirve para aproximar 'quién está conectado' — Streamlit
    no tiene sesión persistente ni evento de cierre."""
    try:
        nombre = usuario.get("nombre", "")
        if not nombre:
            return
        params = (nombre, usuario.get("email", ""), usuario.get("rol", ""), _ahora())
        conn = _connect()
        try:
            if _is_postgres():
                sql = ("INSERT INTO presencia (usuario, email, rol, last_seen) "
                       "VALUES (?, ?, ?, ?) ON CONFLICT (usuario) DO UPDATE SET "
                       "email = EXCLUDED.email, rol = EXCLUDED.rol, last_seen = EXCLUDED.last_seen")
                with conn.cursor() as cur:
                    cur.execute(_sql(sql), params)
                conn.commit()
            else:
                sql = ("INSERT INTO presencia (usuario, email, rol, last_seen) "
                       "VALUES (?, ?, ?, ?) ON CONFLICT(usuario) DO UPDATE SET "
                       "email = excluded.email, rol = excluded.rol, last_seen = excluded.last_seen")
                conn.execute(sql, params)
        finally:
            conn.close()
    except Exception:
        pass


def get_presencia():
    """Presencia de todos los usuarios, del más reciente al más antiguo."""
    conn = _connect()
    try:
        return _fetchall(conn,
                         "SELECT usuario, email, rol, last_seen FROM presencia "
                         "ORDER BY last_seen DESC")
    finally:
        conn.close()


def marcar_en_revision(usuario, folio):
    """Marca que 'usuario' está trabajando el 2do check de 'folio' ahora.
    Best-effort: es un latido de presencia por folio para avisar a otros
    evaluadores y evitar doble esfuerzo."""
    try:
        if not usuario or not folio:
            return
        params = (usuario, folio, _ahora())
        conn = _connect()
        try:
            if _is_postgres():
                sql = ("INSERT INTO en_revision (usuario, folio, last_seen) "
                       "VALUES (?, ?, ?) ON CONFLICT (usuario) DO UPDATE SET "
                       "folio = EXCLUDED.folio, last_seen = EXCLUDED.last_seen")
                with conn.cursor() as cur:
                    cur.execute(_sql(sql), params)
                conn.commit()
            else:
                sql = ("INSERT INTO en_revision (usuario, folio, last_seen) "
                       "VALUES (?, ?, ?) ON CONFLICT(usuario) DO UPDATE SET "
                       "folio = excluded.folio, last_seen = excluded.last_seen")
                conn.execute(sql, params)
        finally:
            conn.close()
    except Exception:
        pass


def folios_en_revision(excluir_usuario=None, ventana_seg=120):
    """{folio: [nombres]} de quienes están trabajando un 2do check ahora
    (latido dentro de ventana_seg segundos), excluyendo opcionalmente a
    una persona. Best-effort: si algo falla, regresa {}."""
    try:
        corte = (datetime.now(_TZ) - timedelta(seconds=ventana_seg)).strftime(
            "%Y-%m-%d %H:%M:%S")
        conn = _connect()
        try:
            filas = _fetchall(conn,
                              "SELECT usuario, folio FROM en_revision "
                              "WHERE last_seen >= ?", (corte,))
        finally:
            conn.close()
    except Exception:
        return {}
    activos = {}
    for f in filas:
        if excluir_usuario and f["usuario"] == excluir_usuario:
            continue
        activos.setdefault(f["folio"], []).append(f["usuario"])
    return activos


def evaluadores_en_folio(folio, excluir_usuario=None, ventana_seg=120):
    """Nombres de quienes están trabajando el 2do check de 'folio' ahora."""
    return folios_en_revision(excluir_usuario, ventana_seg).get(folio, [])
